api/urls.py
from django.urls import path
from .views import *

app_name = 'api'

urlpatterns = [
    path("reviews/", BookReviewListAPIView.as_view(), name="review-list"),
    path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name="review-detail"),
]

books/urls.py
from django.urls import path
from .views import *

app_name = 'books'

urlpatterns = [
    path('', BookView.as_view(), name='list'),
    path('<int:pk>/', BookDetailView.as_view(), name='detail'),
    path('<int:pk>/reviews/', AddReviewVIEW.as_view(), name='reviews'),
    path('<int:book_id>/<int:review_id>/edit/', EditReviewVIEW.as_view(), name='edit_review'),
    path('<int:book_id>/<int:review_id>/delete/confirm/', ConfirmDeleteReviewVIEW.as_view(), name='confirm_delete_review'),
    path('<int:book_id>/<int:review_id>/delete/', DeleteReviewVIEW.as_view(), name='delete_review')
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", landing_page, name="landing_page"),
    path("home/", home_page, name="home_page"),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),
    path("api/", include("api.urls")),
    path('api-auth/', include('rest_framework.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.utils import timezone
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="img.png")

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.stars_given} stars given for {self.book} by {self.user.username}"

books/forms.py
from django import forms

from .models import BookReview


class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = BookReview
        fields = ("stars_given", 'comment')

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from .forms import *
from .models import Book


# Create your views here.

class BookView(View):
    def get(self, request):
        books = Book.objects.all().order_by("id")
        search_book = request.GET.get('q', "")
        if search_book:
            books = books.filter(title__icontains=search_book)
        page_size = request.GET.get('page_size', 2)
        paginator = Paginator(books, page_size)

        page_num = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_num)
        return render(request, 'books/list.html', {'page_obj': page_obj, "search_book": search_book})

class BookDetailView(View):
    def get(self, request, pk):
        book_detail = Book.objects.get(id=pk)
        review_form = BookReviewForm()
        return render(request, 'books/book_detail.html', {'book': book_detail, 'review_form': review_form})


class AddReviewVIEW(LoginRequiredMixin, View):
    def post(self, request, pk):
        book = Book.objects.get(id=pk)
        review_form = BookReviewForm(data=request.POST)

        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                stars_given=review_form.cleaned_data['stars_given'],
                comment=review_form.cleaned_data['comment']
            )
            return redirect(reverse("books:detail", kwargs={"pk": book.id}))
        else:

            return render(request, 'books/book_detail.html', {'book': book, 'review_form': review_form})


class EditReviewVIEW(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review)
        return render(request, 'books/edit_review.html', {"book": book, "review": review, "review_form": review_form})

    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(data=request.POST, instance=review)

        if review_form.is_valid():
            review_form.save()
            return redirect(reverse("books:detail", kwargs={"pk": book.id}))

        return render(request, 'books/edit_review.html', {"book": book, "review": review, "review_form": review_form})


class ConfirmDeleteReviewVIEW(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        return render(request, 'books/confirm_delete_review.html', {"book": book, "review": review})


class DeleteReviewVIEW(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        review.delete()

        messages.success(request, "You have successfully delete this review")
        return redirect(reverse("books:detail", kwargs={"pk": book.id}))

templates/books/book_detail.html
{% extends 'base.html' %}

{% block title %} Book Detail  {% endblock title %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row mb-4">
    <div class="col-2">
        <img class="cover-pic" src="{{book.cover_picture.url}}">
    </div>
    <div class="col-6 ms-4">
        <h3>{{book.title}}</h3>

        <p>
            {{book.description|truncatewords:139}}
        </p>
    </div>
</div>


<div class="row mb-4">
    <div class="col-6">
        <form method="post" action="{% url 'books:reviews'  book.pk %}">
            {% csrf_token %}

            {{review_form|crispy}}

            <button class="btn btn-secondary fw-bold" type="submit">Add</button>
        </form>
    </div>
</div>

{% if book.bookreview_set.exists %}
<h4>Reviews</h4>
    <hr>
    {% for review in book.bookreview_set.all %}

<div class="row">
    <div class="col-2 me-1">
        <img class="profile1-pic ms-3 mb-4" src="{{review.user.profile_picture.url}}">
    </div>
    <div class="col-7">
            <b>{{ review.user.username }}</b> rated it {{review.stars_given}} stars  <span class="fw-lighter ms-3">{{review.created_at}}</span>
            {% if review.user == request.user %}
            <a href="{% url 'books:edit_review' book.id review.id%}"><i class="bi bi-pen-fill"></i></a>
            <a href="{% url 'books:confirm_delete_review' book.id review.id %}"><i class="bi bi-trash"></i></a>
            {% endif %}
            <p class="mt-2 font-monospace">
                {{ review.comment}}
            </p>
    </div>
</div>

    {% endfor %}
{% endif %}
{% endblock content %}

templates/books/confirm_delete_review.html
{% extends 'base.html' %}

{% block title %} Confirm Delete Review {% endblock title %}



{% block content %}

<h1>Are you sure want to delete this review</h1>
    <p>
        <b>Book:</b> {{book.title}}
    </p>
    <p>
        <b>Comment:</b> {{review.comment}}
    </p>

    <a href="{% url 'books:delete_review' book.id review.id %}" class="btn btn-outline-danger">Yes</a> <a href="{% url 'books:detail' book.id %}" class="btn btn-outline-primary">No</a>

{% endblock content %}

templates/books/edit_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Review {% endblock title %}

{% block content %}

<h1>Edit Review</h1>

<div class="row mb-4">
    <div class="col-6">
        <form method="post">
            {% csrf_token %}

            {{review_form|crispy}}

            <button class="btn btn-secondary fw-bold" type="submit">Edit</button>
        </form>
    </div>
</div>

{% endblock content %}

templates/books/list.html
{% extends "base.html" %}

{% block title %}Books Page{% endblock %}
{% load static %}

{% block content %}
    <h1>Books</h1>

    <div class="row mb-3">
        <div class="col-4">
            <form class="d-flex" method="get">
                <input class="form-control me-2" type="text" placeholder="Search" name="q" value="{{ search_query }}">
                <button class="btn btn-success">Search</button>
            </form>
        </div>
    </div>

    {% if page_obj %}
        {% for book in page_obj.object_list %}
            <div class="row mb-3">
                <div class="col-2">
                    <img class="cover-pic" src="{{ book.cover_picture.url }}" alt="Book cover">
                </div>
                <div class="col-6 ms-5">
                    <a href="{% url 'books:detail' book.pk %}">{{ book.title }}</a>
                    <p>{{ book.description|truncatewords:150}}</p>
                </div>
            </div>
        {% endfor %}

        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                {% endif %}
                <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        No books found.
    {% endif %}
{% endblock %}